theme: jekyll-theme-hacker
sass:
    sass_dir: assets/css/

permalink: /:categories/:year/:month/:day/:slug/
timezone: Europe/Amsterdam
author: Anya Helene Bagge
title: Anya Helene Bagge
description:
